### ISSUE TITLE
SplitView PanePlacement = Right throw Exception

### ISSUE THREAD

**Issue by h82258652** [dotMorten/UniversalWPF#15]
![qq 20161201094254](https://cloud.githubusercontent.com/assets/5144550/20778715/97e65190-b7aa-11e6-9450-9e9bfa9ea0f4.jpg)
It seems can not animate HorizontalAlignment property.

**Comment by dotMorten** [comment]
Closing. Not enough information to repro. Feel free to provide more and re-open.
