### ISSUE TITLE
NuGet package

### ISSUE THREAD

**Issue by Wahllow** [dotMorten/UniversalWPF#3]
Hi @dotMorten, would it be possible for you to create a NuGet package?

**Comment by dotMorten** [comment]
Yes totally possible, but I'm not planning on that until the project is a little further along. Until then just compile and add an assembly reference. At least for good old .NET assembly references are still quite simple.

**Comment by Wahllow** [comment]
Good to hear. I was just curious :smile:

**Comment by dotMorten** [comment]
Opening back until done

**Comment by dotMorten** [comment]
Moved the project to use .csproj, so at least now you can just compile to generate the nuget package.

**Comment by dotMorten** [comment]
UniversalWPF.RelativePanel is now on nuget. The other controls still needs lots of work, but if I get them working right will publish as well.
